### PR TITLE
Move span tags to span data

### LINKED ISSUE #728: TracingDriverConnectionFactory calls the deprecated method AbstractMySQLPlatform::getName()
### Environment

* PHP 8.2
* sentry/sentry-symfony:4.8.0

### Steps to Reproduce

`AbstractMySQLPlatform::getName()` was deprecated in https://github.com/doctrine/dbal/issues/4749 but is still used in [`Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverConnectionFactory`](https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Doctrine/DBAL/TracingDriverConnectionFactory.php#L40).

This triggers the following deprecation warning:

```
AbstractMySQLPlatform::getName() is deprecated. Identify platforms by their class. (AbstractMySQLPlatform.php:1209 called by TracingDriverConnectionF
actory.php:40, https://github.com/doctrine/dbal/issues/4749, package doctrine/dbal)
```

Doctrine team suggests to use the class name to identify the platform instead.

As far as I can see the only usage of the platform name is in [`Sentry\SentryBundle\Tracing\Doctrine\DBAL\TracingDriverConnection::getSpanTags()`](https://github.com/getsentry/sentry-symfony/blob/master/src/Tracing/Doctrine/DBAL/TracingDriverConnection.php#L255).

### PR DESCRIPTION
**Pull request by cleptric**
Closes #728

### CODE REVIEW

File: src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php [hunk 1]
```diff
@@ -32,24 +32,24 @@ abstract class AbstractTracingStatement
     protected $sqlQuery;
 
     /**
-     * @var array<string, string> The span tags
+     * @var array<string, string> The span data
      */
-    protected $spanTags;
+    protected $spanData;
```
Comment (ste93cry) [inline src/Tracing/Doctrine/DBAL/AbstractTracingStatement.php:37]: Technically speaking, this is a BC... We should leave the old property (and likely initialize it with an empty `array`), mark it deprecated and add `$spanData`

File: src/Tracing/Doctrine/DBAL/TracingDriverConnectionFactory.php [hunk 2]
```diff
@@ -47,4 +53,29 @@ public function create(Connection $connection, AbstractPlatform $databasePlatfor
 
         return $tracingDriverConnection;
     }
+
+    private function getDatabasePlatform(AbstractPlatform $databasePlatform): string
+    {
+        // https://github.com/open-telemetry/opentelemetry-specification/blob/33113489fb5a1b6da563abb4ffa541447b87f515/specification/trace/semantic_conventions/database.md#connection-level-attributes
+        if ($databasePlatform instanceof AbstractMySQLPlatform) {
```
Comment (ste93cry) [inline src/Tracing/Doctrine/DBAL/TracingDriverConnectionFactory.php:60]: I suggest to use a `switch (true)` where each case is `$databasePlatform instanceof ...`

**Review by ste93cry — CHANGES_REQUESTED** [review]

**Review by HazAT — APPROVED** [review]

**Review by ste93cry — APPROVED** [review]
